# Generated by Django 2.2.7 on 2020-01-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn_13', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=700)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=200, null=True)),
                ('series', models.CharField(max_length=100, null=True)),
                ('volume', models.CharField(max_length=100, null=True)),
                ('ready_for_sale', models.BooleanField()),
                ('publisher', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=300)),
            ],
        ),
    ]
