# Generated by Django 2.2.7 on 2020-01-31 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='primary_author',
        ),
        migrations.AddField(
            model_name='book',
            name='other_authors',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
