# Generated by Django 2.2.7 on 2020-01-31 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200131_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='other_authors',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='series',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='volume',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
