# Generated by Django 2.2.7 on 2020-02-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200131_1405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='book',
            name='linenos',
            field=models.BooleanField(default=False),
        ),
    ]
