# Generated by Django 2.2.7 on 2020-02-14 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200205_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='linenos',
        ),
    ]
