# Generated by Django 2.2.7 on 2020-02-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_book_linenos'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastONIXFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
    ]
