# Generated by Django 2.2.7 on 2020-02-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20200217_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='book',
            name='other_authors',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
