# Generated by Django 2.2.7 on 2020-02-18 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20200217_2052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lastonixfile',
            options={'ordering': [None]},
        ),
    ]
