# Generated by Django 2.2.7 on 2020-02-18 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20200218_0554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lastonixfile',
            options={},
        ),
    ]
