# Generated by Django 2.2.7 on 2020-04-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookstore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='approved_bookstores',
            field=models.ManyToManyField(to='b2bsite.Bookstore'),
        ),
    ]
