# Generated by Django 2.2.7 on 2020-04-20 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2bsite', '0002_auto_20200420_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='approved_bookstores',
            new_name='bookstores',
        ),
    ]
